# Generated by Django 3.2.25 on 2025-01-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
