# Generated by Django 3.2.25 on 2025-02-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteApp', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjct',
            new_name='subject',
        ),
    ]
